// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MarkdownTutor",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MarkdownTutor",
            targets: ["AppModule"],
            bundleIdentifier: "com.powen.MarkdownTutor",
            teamIdentifier: "6ZU6RS59RC",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/gonzalezreal/swift-markdown-ui", "2.0.0"..<"3.0.0"),
        .package(url: "https://github.com/exyte/PopupView", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MarkdownUI", package: "swift-markdown-ui"),
                .product(name: "PopupView", package: "popupview")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)